version: '3' # composeファイルのバーション指定
services:
  apiserver: # service名
    build:
      context: ./apiserver
      dockerfile: docker/Dockerfile
    container_name: mystery-apiserver
    tty: true # コンテナの起動永続化
    volumes:
      - ./apiserver:/go/src/mystery_land/apiserver # マウントディレクトリ指定
    ports:
      - "8888:8888" #コンテナの8080番に転送される。コンテナの8080はポートが開いてる
#    entrypoint:
#      # mysqlが立ち上がるまで待つ
#      - dockerize
#      - -wait
#      - tcp://mysql:3306
    environment:
      MYSQL_DB_HOST: mysql
      MYSQL_DB: mystery_land
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.30
    container_name: mystery-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mystery_land
    ports:
      - 3306:3306
    volumes:
      - ./db/.db-store:/var/lib/mysql
  client:
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile
    container_name: mystery-client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    working_dir: /app
    tty: true
    # command: sh -c "cd assets && yarn install && yarn serve"
